/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bigfoot.ui.produto;

/**
 *
 * @author rodri
 */
public class TelaEditarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaEditarProduto
     */
    public TelaEditarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEditarProduto = new javax.swing.JPanel();
        jLabelEditarModelo = new javax.swing.JLabel();
        jLabelEditarTipo = new javax.swing.JLabel();
        jLabelEditarTamanho = new javax.swing.JLabel();
        jLabelEditarQuantidade = new javax.swing.JLabel();
        jLabelEditarMarca = new javax.swing.JLabel();
        jLabelEditarPreco = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        TextFieldEditarPreco = new javax.swing.JFormattedTextField();
        jTextFieldEditarModelo = new javax.swing.JTextField();
        jTextFieldEditarTipo = new javax.swing.JTextField();
        jTextFieldEditarTamanho = new javax.swing.JTextField();
        jTextFieldEditarMarca = new javax.swing.JTextField();
        TextFieldEditarQuantidade = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar Produto");

        jPanelEditarProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEditarModelo.setText("Modelo:");

        jLabelEditarTipo.setText("Tipo:");

        jLabelEditarTamanho.setText("Tamanho:");

        jLabelEditarQuantidade.setText("Quantidade:");

        jLabelEditarMarca.setText("Marca:");

        jLabelEditarPreco.setText("Preço:");

        jButtonEditar.setText("Editar");

        jButtonCancelar.setText("Cancelar");

        TextFieldEditarPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        TextFieldEditarQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanelEditarProdutoLayout = new javax.swing.GroupLayout(jPanelEditarProduto);
        jPanelEditarProduto.setLayout(jPanelEditarProdutoLayout);
        jPanelEditarProdutoLayout.setHorizontalGroup(
            jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarProdutoLayout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(jButtonEditar))
                    .addGroup(jPanelEditarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabelEditarTamanho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEditarTamanho))
                    .addGroup(jPanelEditarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabelEditarPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldEditarPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEditarQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldEditarQuantidade))
                    .addGroup(jPanelEditarProdutoLayout.createSequentialGroup()
                        .addComponent(jLabelEditarMarca)
                        .addGap(9, 9, 9)
                        .addComponent(jTextFieldEditarMarca))
                    .addGroup(jPanelEditarProdutoLayout.createSequentialGroup()
                        .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEditarTipo)
                            .addComponent(jLabelEditarModelo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEditarModelo)
                            .addComponent(jTextFieldEditarTipo))))
                .addContainerGap())
        );
        jPanelEditarProdutoLayout.setVerticalGroup(
            jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditarModelo)
                    .addComponent(jTextFieldEditarModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditarTipo)
                    .addComponent(jTextFieldEditarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditarTamanho)
                    .addComponent(jTextFieldEditarTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditarMarca)
                    .addComponent(jTextFieldEditarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditarPreco)
                    .addComponent(TextFieldEditarPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEditarQuantidade)
                    .addComponent(TextFieldEditarQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanelEditarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEditarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField TextFieldEditarPreco;
    private javax.swing.JFormattedTextField TextFieldEditarQuantidade;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabelEditarMarca;
    private javax.swing.JLabel jLabelEditarModelo;
    private javax.swing.JLabel jLabelEditarPreco;
    private javax.swing.JLabel jLabelEditarQuantidade;
    private javax.swing.JLabel jLabelEditarTamanho;
    private javax.swing.JLabel jLabelEditarTipo;
    private javax.swing.JPanel jPanelEditarProduto;
    private javax.swing.JTextField jTextFieldEditarMarca;
    private javax.swing.JTextField jTextFieldEditarModelo;
    private javax.swing.JTextField jTextFieldEditarTamanho;
    private javax.swing.JTextField jTextFieldEditarTipo;
    // End of variables declaration//GEN-END:variables
}
