/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bigfoot.ui.produto;

/**
 *
 * @author rodri
 */
public class TelaConsultarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultarProduto
     */
    public TelaConsultarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConsultaProduto = new javax.swing.JPanel();
        jLabelConsultaModelo = new javax.swing.JLabel();
        jLabelConsultaTipo = new javax.swing.JLabel();
        jLabelConsultaMarca = new javax.swing.JLabel();
        jLabelConsultaQuantidade = new javax.swing.JLabel();
        jTextFieldConsultaModelo = new javax.swing.JTextField();
        jTextFieldConsultaTipo = new javax.swing.JTextField();
        jTextFieldConsultaMarca = new javax.swing.JTextField();
        jTextFieldConsultaQuantidade = new javax.swing.JTextField();
        jButtonConsultaProduto = new javax.swing.JButton();
        jButtonCancelarConsultaProduto = new javax.swing.JButton();
        jScrollPaneConsultaProduto = new javax.swing.JScrollPane();
        jTableConsultaProduto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Produto");

        jPanelConsultaProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelConsultaModelo.setText("Modelo:");

        jLabelConsultaTipo.setText("Tipo:");

        jLabelConsultaMarca.setText("Marca:");

        jLabelConsultaQuantidade.setText("Quantidade:");

        jButtonConsultaProduto.setText("Consultar");

        jButtonCancelarConsultaProduto.setText("Cancelar");

        jTableConsultaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Modelo", "Tipo", "Marca", "Tamanho", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneConsultaProduto.setViewportView(jTableConsultaProduto);

        javax.swing.GroupLayout jPanelConsultaProdutoLayout = new javax.swing.GroupLayout(jPanelConsultaProduto);
        jPanelConsultaProduto.setLayout(jPanelConsultaProdutoLayout);
        jPanelConsultaProdutoLayout.setHorizontalGroup(
            jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addGroup(jPanelConsultaProdutoLayout.createSequentialGroup()
                        .addGroup(jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultaProdutoLayout.createSequentialGroup()
                                .addComponent(jLabelConsultaModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldConsultaModelo))
                            .addGroup(jPanelConsultaProdutoLayout.createSequentialGroup()
                                .addComponent(jLabelConsultaMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldConsultaMarca)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelConsultaProdutoLayout.createSequentialGroup()
                                .addComponent(jLabelConsultaTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldConsultaTipo))
                            .addGroup(jPanelConsultaProdutoLayout.createSequentialGroup()
                                .addComponent(jLabelConsultaQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldConsultaQuantidade))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaProdutoLayout.createSequentialGroup()
                        .addComponent(jButtonCancelarConsultaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonConsultaProduto)))
                .addContainerGap())
        );
        jPanelConsultaProdutoLayout.setVerticalGroup(
            jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultaModelo)
                    .addComponent(jTextFieldConsultaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsultaQuantidade)
                    .addComponent(jTextFieldConsultaQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultaMarca)
                    .addComponent(jTextFieldConsultaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelConsultaTipo)
                    .addComponent(jTextFieldConsultaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelConsultaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultaProduto)
                    .addComponent(jButtonCancelarConsultaProduto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConsultaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarConsultaProduto;
    private javax.swing.JButton jButtonConsultaProduto;
    private javax.swing.JLabel jLabelConsultaMarca;
    private javax.swing.JLabel jLabelConsultaModelo;
    private javax.swing.JLabel jLabelConsultaQuantidade;
    private javax.swing.JLabel jLabelConsultaTipo;
    private javax.swing.JPanel jPanelConsultaProduto;
    private javax.swing.JScrollPane jScrollPaneConsultaProduto;
    private javax.swing.JTable jTableConsultaProduto;
    private javax.swing.JTextField jTextFieldConsultaMarca;
    private javax.swing.JTextField jTextFieldConsultaModelo;
    private javax.swing.JTextField jTextFieldConsultaQuantidade;
    private javax.swing.JTextField jTextFieldConsultaTipo;
    // End of variables declaration//GEN-END:variables
}
