/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bigfoot.ui.venda;

/**
 *
 * @author rodri
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVendaCliente = new javax.swing.JPanel();
        jLabelClienteNome = new javax.swing.JLabel();
        jLabelNomeCliente = new javax.swing.JTextField();
        jPanelVendaProduto = new javax.swing.JPanel();
        jLabelVendaModelo1 = new javax.swing.JLabel();
        jLabelVendaTamanho1 = new javax.swing.JLabel();
        jLabelVendaquantidade1 = new javax.swing.JLabel();
        jTextFieldVendaModelo1 = new javax.swing.JTextField();
        jTextFieldVendaTamanho1 = new javax.swing.JTextField();
        jTextFieldVendaQuantidade1 = new javax.swing.JTextField();
        jLabelVendaModelo2 = new javax.swing.JLabel();
        jLabelVendaTamanho2 = new javax.swing.JLabel();
        jLabelVendaquantidade2 = new javax.swing.JLabel();
        jTextFieldVendaModelo2 = new javax.swing.JTextField();
        jTextFieldVendaTamanho2 = new javax.swing.JTextField();
        jTextFieldVendaQuantidade2 = new javax.swing.JTextField();
        jLabelValorVenda = new javax.swing.JLabel();
        jButtonCancelarVenda = new javax.swing.JButton();
        jButtonFinalizarVenda = new javax.swing.JButton();
        jTextFieldVendaModelo3 = new javax.swing.JTextField();
        jTextFieldVendaTamanho3 = new javax.swing.JTextField();
        jTextFieldVendaQuantidade3 = new javax.swing.JTextField();
        jLabelVendaModelo3 = new javax.swing.JLabel();
        jLabelVendaTamanho3 = new javax.swing.JLabel();
        jLabelVendaquantidade3 = new javax.swing.JLabel();
        jLabelVendaModelo4 = new javax.swing.JLabel();
        jLabelVendaTamanho4 = new javax.swing.JLabel();
        jLabelVendaquantidade4 = new javax.swing.JLabel();
        jTextFieldVendaModelo4 = new javax.swing.JTextField();
        jTextFieldVendaTamanho4 = new javax.swing.JTextField();
        jTextFieldVendaQuantidade4 = new javax.swing.JTextField();
        jLabeTotalVenda = new javax.swing.JLabel();
        jLabelPrecoProduto1 = new javax.swing.JLabel();
        jLabelPrecoProduto2 = new javax.swing.JLabel();
        jLabelPrecoProduto3 = new javax.swing.JLabel();
        jLabelPrecoProduto4 = new javax.swing.JLabel();
        jLabel1jLabelPrecoProdutoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda");

        jPanelVendaCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabelClienteNome.setText("Nome:");

        javax.swing.GroupLayout jPanelVendaClienteLayout = new javax.swing.GroupLayout(jPanelVendaCliente);
        jPanelVendaCliente.setLayout(jPanelVendaClienteLayout);
        jPanelVendaClienteLayout.setHorizontalGroup(
            jPanelVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelClienteNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNomeCliente)
                .addGap(112, 112, 112))
        );
        jPanelVendaClienteLayout.setVerticalGroup(
            jPanelVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClienteNome)
                    .addComponent(jLabelNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelVendaProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        jLabelVendaModelo1.setText("Modelo:");

        jLabelVendaTamanho1.setText("Tamanho:");

        jLabelVendaquantidade1.setText("Quantidade:");

        jLabelVendaModelo2.setText("Modelo:");

        jLabelVendaTamanho2.setText("Tamanho:");

        jLabelVendaquantidade2.setText("Quantidade:");

        jLabelValorVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelValorVenda.setText("Total:");

        jButtonCancelarVenda.setText("Cancelar");

        jButtonFinalizarVenda.setText("Finalizar");

        jLabelVendaModelo3.setText("Modelo:");

        jLabelVendaTamanho3.setText("Tamanho:");

        jLabelVendaquantidade3.setText("Quantidade:");

        jLabelVendaModelo4.setText("Modelo:");

        jLabelVendaTamanho4.setText("Tamanho:");

        jLabelVendaquantidade4.setText("Quantidade:");

        jLabeTotalVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeTotalVenda.setText("Valor");

        jLabelPrecoProduto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrecoProduto1.setText("0");

        jLabelPrecoProduto2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrecoProduto2.setText("0");

        jLabelPrecoProduto3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrecoProduto3.setText("0");

        jLabelPrecoProduto4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPrecoProduto4.setText("0");

        jLabel1jLabelPrecoProdutoTotal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1jLabelPrecoProdutoTotal.setText("0");

        javax.swing.GroupLayout jPanelVendaProdutoLayout = new javax.swing.GroupLayout(jPanelVendaProduto);
        jPanelVendaProduto.setLayout(jPanelVendaProdutoLayout);
        jPanelVendaProdutoLayout.setHorizontalGroup(
            jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCancelarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFinalizarVenda)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaProdutoLayout.createSequentialGroup()
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelValorVenda))
                            .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabelVendaModelo4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVendaModelo4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                                        .addComponent(jLabelVendaTamanho4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVendaTamanho4, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelVendaquantidade4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVendaQuantidade4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))))
                            .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabelVendaModelo3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVendaModelo3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                                        .addComponent(jLabelVendaTamanho3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVendaTamanho3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelVendaquantidade3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVendaQuantidade3, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVendaProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelVendaModelo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVendaModelo1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVendaProdutoLayout.createSequentialGroup()
                                .addComponent(jLabelVendaTamanho1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVendaTamanho1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVendaquantidade1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVendaQuantidade1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVendaProdutoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelVendaModelo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVendaModelo2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVendaProdutoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabelVendaTamanho2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVendaTamanho2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVendaquantidade2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVendaQuantidade2)))
                        .addGap(55, 55, 55)
                        .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPrecoProduto1)
                                .addComponent(jLabelPrecoProduto2)
                                .addComponent(jLabelPrecoProduto3)
                                .addComponent(jLabelPrecoProduto4))
                            .addComponent(jLabel1jLabelPrecoProdutoTotal, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(13, 13, 13))
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabeTotalVenda)))
                .addGap(33, 33, 33))
        );
        jPanelVendaProdutoLayout.setVerticalGroup(
            jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                .addComponent(jLabeTotalVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVendaModelo1)
                    .addComponent(jTextFieldVendaModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVendaTamanho1)
                    .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldVendaTamanho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelVendaquantidade1)
                        .addComponent(jTextFieldVendaQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPrecoProduto1)))
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVendaModelo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVendaModelo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVendaTamanho2)
                            .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldVendaTamanho2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelVendaquantidade2)
                                .addComponent(jTextFieldVendaQuantidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelPrecoProduto2)))
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVendaModelo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVendaModelo3)))
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelPrecoProduto3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVendaTamanho3)
                    .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldVendaTamanho3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelVendaquantidade3)
                        .addComponent(jTextFieldVendaQuantidade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldVendaModelo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelVendaModelo4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVendaTamanho4)
                            .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldVendaTamanho4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelVendaquantidade4)
                                .addComponent(jTextFieldVendaQuantidade4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelVendaProdutoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabelPrecoProduto4)))
                .addGap(18, 18, 18)
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorVenda)
                    .addComponent(jLabel1jLabelPrecoProdutoTotal))
                .addGap(28, 28, 28)
                .addGroup(jPanelVendaProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarVenda)
                    .addComponent(jButtonFinalizarVenda))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVendaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelVendaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelVendaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarVenda;
    private javax.swing.JButton jButtonFinalizarVenda;
    private javax.swing.JLabel jLabeTotalVenda;
    private javax.swing.JLabel jLabel1jLabelPrecoProdutoTotal;
    private javax.swing.JLabel jLabelClienteNome;
    private javax.swing.JTextField jLabelNomeCliente;
    private javax.swing.JLabel jLabelPrecoProduto1;
    private javax.swing.JLabel jLabelPrecoProduto2;
    private javax.swing.JLabel jLabelPrecoProduto3;
    private javax.swing.JLabel jLabelPrecoProduto4;
    private javax.swing.JLabel jLabelValorVenda;
    private javax.swing.JLabel jLabelVendaModelo1;
    private javax.swing.JLabel jLabelVendaModelo2;
    private javax.swing.JLabel jLabelVendaModelo3;
    private javax.swing.JLabel jLabelVendaModelo4;
    private javax.swing.JLabel jLabelVendaTamanho1;
    private javax.swing.JLabel jLabelVendaTamanho2;
    private javax.swing.JLabel jLabelVendaTamanho3;
    private javax.swing.JLabel jLabelVendaTamanho4;
    private javax.swing.JLabel jLabelVendaquantidade1;
    private javax.swing.JLabel jLabelVendaquantidade2;
    private javax.swing.JLabel jLabelVendaquantidade3;
    private javax.swing.JLabel jLabelVendaquantidade4;
    private javax.swing.JPanel jPanelVendaCliente;
    private javax.swing.JPanel jPanelVendaProduto;
    private javax.swing.JTextField jTextFieldVendaModelo1;
    private javax.swing.JTextField jTextFieldVendaModelo2;
    private javax.swing.JTextField jTextFieldVendaModelo3;
    private javax.swing.JTextField jTextFieldVendaModelo4;
    private javax.swing.JTextField jTextFieldVendaQuantidade1;
    private javax.swing.JTextField jTextFieldVendaQuantidade2;
    private javax.swing.JTextField jTextFieldVendaQuantidade3;
    private javax.swing.JTextField jTextFieldVendaQuantidade4;
    private javax.swing.JTextField jTextFieldVendaTamanho1;
    private javax.swing.JTextField jTextFieldVendaTamanho2;
    private javax.swing.JTextField jTextFieldVendaTamanho3;
    private javax.swing.JTextField jTextFieldVendaTamanho4;
    // End of variables declaration//GEN-END:variables
}
